export enum ActionTypes {
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE',
  FETCH_BACKGROUND_IMAGE = 'FETCH_BACKGROUND_IMAGE',
  FETCH_BACKGROUND_IMAGE_SUCCESS = 'FETCH_BACKGROUND_IMAGE_SUCCESS',

  SIGN_UP='SIGN_UP',
  SIGN_UP_SUCCESS='SIGN_UP_SUCCESS',

  SIGN_IN='SIGN_IN',
  SIGN_IN_SUCCESS='SIGN_IN_SUCCESS'

}

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export type REQUEST_ARTICLES = typeof REQUEST_ARTICLES
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'
export type RECEIVE_ARTICLES = typeof RECEIVE_ARTICLES

// blog info const
export const REQUEST_INFO = 'REQUEST_INFO'
export type REQUEST_INFO = typeof REQUEST_INFO
export const RECEIVE_INFO = 'RECEIVE_INFO'
export type RECEIVE_INFO = typeof RECEIVE_INFO

// blog article const
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE'
export type REQUEST_ARTICLE = typeof REQUEST_ARTICLE
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE'
export type RECEIVE_ARTICLE = typeof RECEIVE_ARTICLE